name: Build ARM64 DEB Package (QEMU Docker)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Ensure qemu-user-static available
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build DEB inside arm64 container and produce .deb
        env:
          PACKAGE_OUTPUT_DIR: /work/output
        run: |
          docker run --rm \
            --platform linux/arm64 \
            -v "${{ github.workspace }}":/work \
            -w /work \
            ubuntu:22.04 bash -euxc "
              apt-get update
              apt-get install -y --no-install-recommends \
                dpkg-dev debhelper devscripts debhelper-compat \
                qemu-user-static crossbuild-essential-arm64 ca-certificates \
                build-essential fakeroot
              if [ ! -d ./debian ]; then
                echo 'ERROR: ./debian not found' >&2; exit 2
              fi
              # Build: dpkg-buildpackage will place .deb in parent dir (/)
              dpkg-buildpackage -us -uc -aarm64
            "

      - name: Collect produced .deb
        run: |
          ls -la ../*.deb || ls -la ./*.deb || true

      - name: Upload DEB package
        uses: actions/upload-artifact@v4
        with:
          name: deb-package
          path: ../*.deb
