name: Build ARM64 DEB Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ docker login -u robertodoreboque }}
        password: ${{ dckr_pat_6H39bPySf1mpgL34dqXZjMhWn2o }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: yourusername/yourapp:latest
        build-args: |
          BUILDPLATFORM=linux/arm64

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y dpkg-dev debhelper

    - name: Build DEB package
      run: dpkg-buildpackage -us -uc -aarm64

    - name: Upload DEB package
      uses: actions/upload-artifact@v4
      with:
        name: deb-package
        path: ../*.deb
